# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import weather_pb2 as weather__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in weather_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestServiceStub:
    """Streamer -> coordinator.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRecords = channel.stream_unary(
                '/weather.IngestService/StreamRecords',
                request_serializer=weather__pb2.IngestMessage.SerializeToString,
                response_deserializer=weather__pb2.IngestSummary.FromString,
                _registered_method=True)


class IngestServiceServicer:
    """Streamer -> coordinator.
    """

    def StreamRecords(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRecords': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamRecords,
                    request_deserializer=weather__pb2.IngestMessage.FromString,
                    response_serializer=weather__pb2.IngestSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService:
    """Streamer -> coordinator.
    """

    @staticmethod
    def StreamRecords(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/weather.IngestService/StreamRecords',
            weather__pb2.IngestMessage.SerializeToString,
            weather__pb2.IngestSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.stream_unary(
                '/weather.WorkerService/Process',
                request_serializer=weather__pb2.RecordBatch.SerializeToString,
                response_deserializer=weather__pb2.WorkerAck.FromString,
                _registered_method=True)
        self.GetPartial = channel.unary_unary(
                '/weather.WorkerService/GetPartial',
                request_serializer=weather__pb2.Empty.SerializeToString,
                response_deserializer=weather__pb2.PartialState.FromString,
                _registered_method=True)
        self.GetInfo = channel.unary_unary(
                '/weather.WorkerService/GetInfo',
                request_serializer=weather__pb2.Empty.SerializeToString,
                response_deserializer=weather__pb2.WorkerInfo.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/weather.WorkerService/Reset',
                request_serializer=weather__pb2.Empty.SerializeToString,
                response_deserializer=weather__pb2.Empty.FromString,
                _registered_method=True)


class WorkerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Process(self, request_iterator, context):
        """One long-lived client stream per ingest session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.stream_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=weather__pb2.RecordBatch.FromString,
                    response_serializer=weather__pb2.WorkerAck.SerializeToString,
            ),
            'GetPartial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartial,
                    request_deserializer=weather__pb2.Empty.FromString,
                    response_serializer=weather__pb2.PartialState.SerializeToString,
            ),
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=weather__pb2.Empty.FromString,
                    response_serializer=weather__pb2.WorkerInfo.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=weather__pb2.Empty.FromString,
                    response_serializer=weather__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Process(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/weather.WorkerService/Process',
            weather__pb2.RecordBatch.SerializeToString,
            weather__pb2.WorkerAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPartial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.WorkerService/GetPartial',
            weather__pb2.Empty.SerializeToString,
            weather__pb2.PartialState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.WorkerService/GetInfo',
            weather__pb2.Empty.SerializeToString,
            weather__pb2.WorkerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.WorkerService/Reset',
            weather__pb2.Empty.SerializeToString,
            weather__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class QueryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnalytics = channel.unary_unary(
                '/weather.QueryService/GetAnalytics',
                request_serializer=weather__pb2.QueryRequest.SerializeToString,
                response_deserializer=weather__pb2.AnalyticsReport.FromString,
                _registered_method=True)


class QueryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalytics,
                    request_deserializer=weather__pb2.QueryRequest.FromString,
                    response_serializer=weather__pb2.AnalyticsReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.QueryService/GetAnalytics',
            weather__pb2.QueryRequest.SerializeToString,
            weather__pb2.AnalyticsReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
