# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'document.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\x12\tcollabdoc\">\n\x15\x43reateDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0finitial_content\x18\x02 \x01(\t\"7\n\x16\x43reateDocumentResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x12GetDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"E\n\x13GetDocumentResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x04\"V\n\x13\x45\x64itDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\r\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\"F\n\x14\x45\x64itDocumentResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x04\"0\n\rUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"\x8e\x01\n\x0e\x44ocumentUpdate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x04\x12\x11\n\tedited_by\x18\x04 \x01(\t\x12\x10\n\x08position\x18\x05 \x01(\r\x12\x15\n\rinserted_text\x18\x06 \x01(\t\x12\x10\n\x08snapshot\x18\x07 \x01(\x08\x32\xd4\x02\n\x0f\x44ocumentService\x12U\n\x0e\x43reateDocument\x12 .collabdoc.CreateDocumentRequest\x1a!.collabdoc.CreateDocumentResponse\x12L\n\x0bGetDocument\x12\x1d.collabdoc.GetDocumentRequest\x1a\x1e.collabdoc.GetDocumentResponse\x12O\n\x0c\x45\x64itDocument\x12\x1e.collabdoc.EditDocumentRequest\x1a\x1f.collabdoc.EditDocumentResponse\x12K\n\x12SubscribeToUpdates\x12\x18.collabdoc.UpdateRequest\x1a\x19.collabdoc.DocumentUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEDOCUMENTREQUEST']._serialized_start=29
  _globals['_CREATEDOCUMENTREQUEST']._serialized_end=91
  _globals['_CREATEDOCUMENTRESPONSE']._serialized_start=93
  _globals['_CREATEDOCUMENTRESPONSE']._serialized_end=148
  _globals['_GETDOCUMENTREQUEST']._serialized_start=150
  _globals['_GETDOCUMENTREQUEST']._serialized_end=184
  _globals['_GETDOCUMENTRESPONSE']._serialized_start=186
  _globals['_GETDOCUMENTRESPONSE']._serialized_end=255
  _globals['_EDITDOCUMENTREQUEST']._serialized_start=257
  _globals['_EDITDOCUMENTREQUEST']._serialized_end=343
  _globals['_EDITDOCUMENTRESPONSE']._serialized_start=345
  _globals['_EDITDOCUMENTRESPONSE']._serialized_end=415
  _globals['_UPDATEREQUEST']._serialized_start=417
  _globals['_UPDATEREQUEST']._serialized_end=465
  _globals['_DOCUMENTUPDATE']._serialized_start=468
  _globals['_DOCUMENTUPDATE']._serialized_end=610
  _globals['_DOCUMENTSERVICE']._serialized_start=613
  _globals['_DOCUMENTSERVICE']._serialized_end=953
# @@protoc_insertion_point(module_scope)
