# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import document_pb2 as document__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in document_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub:
    """Multi-user collaborative document service.

    Documents live in server memory.  Any client may create, read and edit a
    document; clients that have subscribed to a document receive its full new
    content over a server-streaming RPC every time it changes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDocument = channel.unary_unary(
                '/collabdoc.DocumentService/CreateDocument',
                request_serializer=document__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=document__pb2.CreateDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/collabdoc.DocumentService/GetDocument',
                request_serializer=document__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=document__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.EditDocument = channel.unary_unary(
                '/collabdoc.DocumentService/EditDocument',
                request_serializer=document__pb2.EditDocumentRequest.SerializeToString,
                response_deserializer=document__pb2.EditDocumentResponse.FromString,
                _registered_method=True)
        self.SubscribeToUpdates = channel.unary_stream(
                '/collabdoc.DocumentService/SubscribeToUpdates',
                request_serializer=document__pb2.UpdateRequest.SerializeToString,
                response_deserializer=document__pb2.DocumentUpdate.FromString,
                _registered_method=True)


class DocumentServiceServicer:
    """Multi-user collaborative document service.

    Documents live in server memory.  Any client may create, read and edit a
    document; clients that have subscribed to a document receive its full new
    content over a server-streaming RPC every time it changes.
    """

    def CreateDocument(self, request, context):
        """Creates a new document.  Fails with ALREADY_EXISTS if the name is taken.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Returns the current content of a document.  NOT_FOUND if it does not exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditDocument(self, request, context):
        """Inserts `text` at character offset `position`.  OUT_OF_RANGE if the
        position is past the end of the document, NOT_FOUND if the document does
        not exist.  The response carries the content *after* this edit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToUpdates(self, request, context):
        """Server-streaming subscription.  The first message is a snapshot of the
        document as it stands (snapshot = true), so the subscriber is in sync from
        the moment the stream is live; then one DocumentUpdate per committed edit
        until the client cancels.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=document__pb2.CreateDocumentRequest.FromString,
                    response_serializer=document__pb2.CreateDocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=document__pb2.GetDocumentRequest.FromString,
                    response_serializer=document__pb2.GetDocumentResponse.SerializeToString,
            ),
            'EditDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.EditDocument,
                    request_deserializer=document__pb2.EditDocumentRequest.FromString,
                    response_serializer=document__pb2.EditDocumentResponse.SerializeToString,
            ),
            'SubscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUpdates,
                    request_deserializer=document__pb2.UpdateRequest.FromString,
                    response_serializer=document__pb2.DocumentUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collabdoc.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collabdoc.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService:
    """Multi-user collaborative document service.

    Documents live in server memory.  Any client may create, read and edit a
    document; clients that have subscribed to a document receive its full new
    content over a server-streaming RPC every time it changes.
    """

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdoc.DocumentService/CreateDocument',
            document__pb2.CreateDocumentRequest.SerializeToString,
            document__pb2.CreateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdoc.DocumentService/GetDocument',
            document__pb2.GetDocumentRequest.SerializeToString,
            document__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collabdoc.DocumentService/EditDocument',
            document__pb2.EditDocumentRequest.SerializeToString,
            document__pb2.EditDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/collabdoc.DocumentService/SubscribeToUpdates',
            document__pb2.UpdateRequest.SerializeToString,
            document__pb2.DocumentUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
